/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Audiobook {
  'id' : string,
  'duration' : string,
  'coverEmoji' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'razorpayUrlINR' : string,
  'razorpayUrlUSD' : string,
  'priceINR' : bigint,
  'priceUSD' : bigint,
  'narrator' : string,
}
export interface BlogPost {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'excerpt' : string,
  'category' : string,
}
export interface Book {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'featured' : boolean,
  'audiobookLink' : [] | [string],
  'description' : string,
  'genre' : string,
  'formats' : Array<BookFormat>,
}
export type BookFormat = { 'paperback' : string } |
  { 'kindle' : string };
export interface Coupon {
  'discountValue' : bigint,
  'expiryDate' : bigint,
  'code' : string,
  'discountType' : string,
  'usageCount' : bigint,
  'isActive' : boolean,
  'maxUsages' : bigint,
  'currency' : string,
}
export interface MerchItem {
  'id' : string,
  'razorpayUrl' : string,
  'coverEmoji' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'priceINR' : bigint,
  'priceUSD' : bigint,
}
export interface Order {
  'id' : string,
  'razorpayPaymentId' : string,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'currency' : string,
  'notes' : string,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'name' : string,
  'productId' : string,
  'currency' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Review {
  'bookId' : string,
  'reviewerName' : string,
  'email' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface Setting { 'key' : string, 'value' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  'addBook' : ActorMethod<[Book], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addSubscriber' : ActorMethod<[string], undefined>,
  'createAudiobook' : ActorMethod<[Audiobook], undefined>,
  'createCoupon' : ActorMethod<[Coupon], undefined>,
  'createMerchItem' : ActorMethod<[MerchItem], undefined>,
  'createOrder' : ActorMethod<[Order], undefined>,
  'deleteAudiobook' : ActorMethod<[string], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'deleteCoupon' : ActorMethod<[string], undefined>,
  'deleteMerchItem' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'getAllSettings' : ActorMethod<[], Array<Setting>>,
  'getAudiobook' : ActorMethod<[string], [] | [Audiobook]>,
  'getAudiobooks' : ActorMethod<[], Array<Audiobook>>,
  'getAuthorBio' : ActorMethod<[], string>,
  'getBlogPost' : ActorMethod<[string], BlogPost>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBook' : ActorMethod<[string], Book>,
  'getBooks' : ActorMethod<[], Array<Book>>,
  'getCoupon' : ActorMethod<[string], [] | [Coupon]>,
  'getCoupons' : ActorMethod<[], Array<Coupon>>,
  'getMerchItem' : ActorMethod<[string], [] | [MerchItem]>,
  'getMerchItems' : ActorMethod<[], Array<MerchItem>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getReviews' : ActorMethod<[string], Array<Review>>,
  'getSetting' : ActorMethod<[string], [] | [Setting]>,
  'getSubscribers' : ActorMethod<[], Array<string>>,
  'incrementCouponUsage' : ActorMethod<[string], undefined>,
  'removeSubscriber' : ActorMethod<[string], undefined>,
  'updateAudiobook' : ActorMethod<[Audiobook], undefined>,
  'updateAuthorBio' : ActorMethod<[string], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateBook' : ActorMethod<[Book], undefined>,
  'updateMerchItem' : ActorMethod<[MerchItem], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateSetting' : ActorMethod<[Setting], undefined>,
  'validateCoupon' : ActorMethod<[string], [] | [Coupon]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];